name: triplea-linux # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2.5.22294' # just for humans, typically '1.2+git' or '1.3.2'
summary: TripleA is a free online turn based strategy game and board game engine,
description: |
  TripleA is a free online turn based strategy game and board game engine, similar to such board games as Axis &amp; Allies or Risk. TripleA comes with multiple games and over 100 more games can be downloaded from the user community. Supports single player vs AI, hot-seat, Play by Email and Forum, and a hosted Online lobby for live play online.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  triplea_icon.png
title: TripleA

apps:
  triplea:
    command: TripleA_2.5.22294_unix.sh
parts:
  triplea:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      triplea: build/
      triplea.1: man/man1/

architectures:
  - build-on: amd64

